# docker-compose.yml
version: "2"
services:
  www:
    image: front-wooadmin:1.0
    restart: always
    depends_on:
      - app
    expose:
      - "80"
    # volumes:
      # - /Users/kbs/git/peladonerd/varios/1/www:/usr/share/nginx/html:ro
      # - //d/storeDocker/html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=wooadmin.apps.com.pe,www.wooadmin.apps.com.pe
      - LETSENCRYPT_HOST=wooadmin.apps.com.pe,www.wooadmin.apps.com.pe
      - LETSENCRYPT_EMAIL=miguekos1233@gmail.com

  app:
    container_name: api-wooadmin
    image: api-wooadmin:1.0
    # build: .
    command: python3 -u main.py
    # volumes:
    #   - ./:/code/
    ports:
      - "8050:8050"

networks:
  default:
    external:
      name: nginx-proxy_default
